# Default values for iam-service-account-key.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# https://cloud.google.com/config-connector/docs/reference/resource-docs/iam/iamserviceaccountkey

global:
  # Add labels from a parent chart to all manifests.
  # Google Cloud labels only support hyphens (-), underscores (_), lowercase characters and numbers.
  labels: {}

  # The Google Project ID.
  # [Required]
  projectID: null

  # Google project number, not the ID. This is used to give the default pubsub service account
  # access to deadletter topics. Get a list with the "gcloud projects list" command.
  projectNumber: null

# Below property sets a ArgoCD Sync Wave annotation on all resources. Set it to "false" to disable it.
# https://argo-cd.readthedocs.io/en/stable/user-guide/sync-waves/
argoSyncWave: -5

# Below labels and annotations will be set on all resources.
annotations: {}

# Google Cloud labels only support hyphens (-), underscores (_), lowercase characters and numbers.
labels: {}

############################################################
#                         Topics                           #
############################################################

# Global publishers will get the publisher role on all topics in this chart, except deadletter topics.
# The list will be merged with the publishers set on each specific topic.

# A list of service accounts names without the "@<projectid>.iam.gserviceaccount.com" belonging to your Google project.
globalPublishers: []
  # - <service-account>

# A list of service accounts using the full ID. Used for services accounts outside your Google project.
externalGlobalPublishers: []
  # - <service-account-name>@<project-id>.iam.gserviceaccount.com

topics: {}
  # # The "topicShortName01" is not used for anything other than for you to reference in an environment values file.
  # # Each short name must be unique.
  # topicShortName01:
  #   name: my-topic-name-01
  #
  #   # Set below property to true to create the necessary policy bindings for a deadletter topic.
  #   # (The default pubsub service account will get publisher role)
  #   isDeadletterTopic: false
  #
  #   # When enabled, retains messages on the Topic for up to 31 days after they get acknowledged. This feature is not free.
  #   # Cannot be more than 31 days or less than 10 minutes. Value is en seconds and ends with "s" eg. "600s".
  #   messageRetentionDuration: null
  #
  #   # A list of service accounts names without the "@<projectid>.iam.gserviceaccount.com" belonging to your Google project.
  #   publishers: []
  #     # - <service-account>
  #
  #   # A list of service accounts using the full ID. Used for services accounts outside your Google project.
  #   externalPublishers: []
  #     # - <service-account>@<project-id>.iam.gserviceaccount.com

  # # Below example is a minumum configuration of a topic. No deadletter topic or no messageRetentionDuration.
  # topicShortName02:
  #   name: my-topic-name-02

  # # Below is an example of a deadletter topic.
  # topicShortName03:
  #   name: deadletter.my-topic-name
  #   isDeadletterTopic: true

  # # Below is an example of a topic using a schema.
  # # Create a schema and reference the name of it.
  # topicShortName04:
  #   name: my-topic-name-04
  #   schemaNameRef: my-schema-name

############################################################
#                      Subscriptions                       #
############################################################

# Below list of service account ID's will be given the subscriber role on all subscriptions.
globalSubscribers: []
  # - <service-account>

# Below list of service account ID's will be given the subscriber role on all subscriptions.
externalGlobalSubscribers: []
  # - <service-account-name>@<project-id>.iam.gserviceaccount.com

# Below specs will be merged into all subscriptions specs.
# They can be overwritten on each subscription if pleased.
globalSubscriptionSpecs: {}
  # retryPolicy:
  #   maximumBackoff: 600s
  #   minimumBackoff: 500s

subscriptions: {}
  # # The "subscriptionShortName01" is not used for anything other than for you to reference in an environment values file.
  # # Each short name must be unique.
  # subscriptionShortName01:
  #   name: my-sub-name-01
  #
  #   # A list of full service accounts ID's to get the subscriber role on this subscription.
  #   subscribers: []
  #     # - <service-account>
  #
  #   # A list of full service accounts ID's to get the subscriber role on this subscription.
  #   externalSubscribers: []
  #     # - <service-account-name>@<project-id>.iam.gserviceaccount.com
  #
  #   # Below spec block supports all values from the documentation.
  #   # https://cloud.google.com/config-connector/docs/reference/resource-docs/pubsub/pubsubsubscription#spec
  #   spec:
  #     topicRef:
  #       name: my-topic-name-01
  #     deadLetterPolicy:
  #       deadLetterTopicRef:
  #         name: deadletter.my-topic-name
  #     retryPolicy:
  #       maximumBackoff: 200s
  #       minimumBackoff: 100s

  # # Below example is a minumum configuration of a subscription.
  # subscriptionShortName02:
  #   name: my-sub-name-02
  #   spec:
  #     topicRef:
  #       name: my-topic-name-02

############################################################
#                      Topic Schemas                       #
############################################################

# Remeber a schema is immutable. When first created you cannot change it.
# You will have to create a new version and migrate to it.

topicSchemas: {}
  # # The "schemaShortName01" is not used for anything other than for you to reference in an environment values file.
  # # Each short name must be unique.
  # schemaShortName01:
  #   name: my-schema-name
  #
  #   # Can be PROTOCOL_BUFFER or AVRO
  #   type: AVRO
  #
  #   # The actual schema in PROTOCOL_BUFFER or AVRO.
  #   definition: |
  #     {
  #      "type" : "record",
  #      "name" : "Avro",
  #      "fields" : [
  #        {
  #          "name" : "StringField",
  #          "type" : "string"
  #        },
  #        {
  #          "name" : "FloatField",
  #          "type" : "float"
  #        },
  #        {
  #          "name" : "BooleanField",
  #          "type" : "boolean"
  #        }
  #      ]
  #     }
