# Policy for granting
{{- if or .Values.serviceAccounts .Values.makeAllFilesInThisBucketPublic }}
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: {{ .Values.name }}-roles
  annotations:
    argocd.argoproj.io/sync-wave: {{ $.Values.argoSyncWave | quote }}
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "storagebucket.labels" $ | nindent 4 }}
    {{- range $k, $v := $.Values.labels }}
    {{- printf "%s: %s" $k ($v | quote) | nindent 4 }}
    {{- end }}
spec:
  resourceRef:
    apiVersion: storage.cnrm.cloud.google.com/v1beta1
    kind: StorageBucket
    name: {{ $.Values.name }}
  bindings:
    {{- if .Values.makeAllFilesInThisBucketPublic }}
    - role: roles/storage.objectViewer
      members:
        - member: allUsers
    {{- end }}
    {{- range $sa := .Values.serviceAccounts }}
    - role: {{ $sa.role }}
      members:
        {{- if (.name | contains "@") }}
        - member: "serviceAccount:{{ .name }}"
        {{- else }}
        - memberFrom:
            serviceAccountRef:
              name: {{ .name }}
        {{- end -}}
    {{- end }}
{{- end }}
---
