apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  name: {{ .Values.name | required "A StorageBucket resource name is required." }}
  {{- if or (.Values.annotations) (.Values.argoSyncWave) }}
  annotations:
    {{- with .Values.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.argoSyncWave }}
    argocd.argoproj.io/sync-wave: {{ .Values.argoSyncWave | quote }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "storagebucket.labels" $ | nindent 4 }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.spec }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
