# Default values for big-query.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# https://cloud.google.com/config-connector/docs/reference/resource-docs/bigquery/bigquerydataset

global:
  # Add labels from a parent chart to all manifests.
  # Google Cloud labels only support hyphens (-), underscores (_), lowercase characters and numbers.
  labels: {}

  # The Google Project ID.
  # [Required]
  projectID: null

# The full ID of the Config Connector service account which will create the BigQuery resources.
# This is due to a limitation on the CC BigQuery provider.
# See https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/127 for more details.
# [Required]
configConnectorSaId: null

dataSets: {}
  # # The "dataSetShortName01" is not used for anything other than for you to reference the object in an environment values file.
  # # Each short name must be unique.
  # dataSetShortName01:
  #   # Dataset name can only include lowercase alphanumeric characters and hyphens (-).
  #   # The dataset name will be converted to snakecase in BigQuery, eg. my-dataset-name will be my_dataset_name.
  #   name: my-dataset-name
  #   description: "BigQuery Dataset Sample"
  #   permissions:
  #     # Below fields are used for SA's  that do not belong to the "global.projectID".
  #     # They must end with ".iam.gserviceaccount.com" or they will not be added.
  #     externalWriter:
  #       - <service-account-name>@<project-id>.iam.gserviceaccount.com
  #     externalReader:
  #       - <service-account-name>@<project-id>.iam.gserviceaccount.com
  #
  #     # Below fields only takes the names of the SA. The "global.projectID" will be used to create the rest of the ID.
  #     writer:
  #       - <service-account-name>
  #     reader:
  #       - <service-account-name>
  #
  #   tables:
  #     # The table name can only include lowercase alphanumeric characters and hyphens (-).
  #     # The table name will be converted to pascalcase in BigQuery, eg. my-table-name will be MyTableName.
  #     - name: my-table-name
  #       description: BigQuery Sample Table
  #       maxStaleness: some staleness string
  #       schema: |
  #         [
  #           {
  #             "mode": "NULLABLE",
  #             "name": "ColumnName01",
  #             "type": "STRING"
  #           },
  #           {
  #             "mode": "NULLABLE",
  #             "name": "ColumnName02",
  #             "type": "INTEGER"
  #           },
  #           {
  #             "mode": "NULLABLE",
  #             "name": "ColumnName03",
  #             "type": "TIMESTAMP"
  #           },
  #           {
  #             "mode": "NULLABLE",
  #             "name": "ColumnName04",
  #             "type": "NUMERIC"
  #           },
  #           {
  #             "mode": "NULLABLE",
  #             "name": "ColumnName05",
  #             "type": "BOOLEAN"
  #           }
  #         ]
  #
  #       timePartitioning:
  #         field: ReadOn
  #         requirePartitionFilter: false
  #         type: DAY
  #
  #     - name: my-view-name
  #       description: BigQuery Sample View
  #
  #       view:
  #         query: |
  #           SELECT some FROM table
  #
  #     - name: my-materialized-view-name
  #       description: BigQuery Sample View
  #
  #       materializedView:
  #         allowNonIncrementalDefinition: false # Immutable
  #         enableRefresh: true
  #         refreshIntervalMs: "1800000"
  #         query: |
  #           SELECT some FROM table
