{{ range $dataset := .Values.dataSets }}
{{ range $dataset.tables }}
apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  name: {{ include "big-query.dataset-name" $dataset }}-{{ include "big-query.table-name" . }}
  {{- if and .schema (not .view) (not .materializedView) }}
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
  {{- end }}
  labels:
    dataset: {{ include "big-query.dataset-name" $dataset }}
    {{- include "big-query.labels" $ | nindent 4 }}
    {{- with .labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  description: {{ .description | quote }}
  resourceID: {{ .name | camelcase }}
  datasetRef:
    name: {{ include "big-query.dataset-name" $dataset }}
  {{- if .externalDataConfiguration }}
  externalDataConfiguration: {{ .externalDataConfiguration | toYaml | nindent 4 }}
  {{- end }}

  {{- if .view }}
  view:
    useLegacySql: {{ .view.useLegacySql | default false }}
    query: | {{ .view.query | nindent 6 }}
  {{- end }}

  {{- if and .timePartitioning (not .view) (not .materializedView)}}
  timePartitioning: {{ .timePartitioning | toYaml | nindent 4 }}
  {{- end }}

  {{- if and .schema (not .view) (not .materializedView) }}
  schema: | {{ .schema | nindent 4 }}
  {{- end }}

  {{- if and .materializedView (not .view) }}
  {{- with .materializedView }}
  materializedView:
    allowNonIncrementalDefinition: {{ .allowNonIncrementalDefinition }}
    enableRefresh: {{ .enableRefresh }}
    refreshIntervalMs: {{ .refreshIntervalMs }}
    query: | {{ .query | nindent 6 }}
  {{- end }}
  {{- end }}
---
{{- end }}
{{- end }}
