############################################################
#                   PubSub Subscriptions                   #
############################################################

{{- range $sub := .Values.subscriptions }}

{{- if gt (len $sub.name) 54 }}
{{- fail (printf "subscription name [%s, len: %d] too long. must have max length of 54." $sub.name (len $sub.name)) }}
{{- end }}

apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSubscription
metadata:
  name: {{ $sub.name }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $.Values.argoSyncWave | quote }}
    {{- with $.Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "pubsub.labels" $ | nindent 4 }}
    {{- range $k, $v := $.Values.labels }}
    {{- printf "%s: %s" $k ($v | quote) | nindent 4 }}
    {{- end }}
spec:
{{- deepCopy $.Values.globalSubscriptionSpecs | merge $sub.spec | toYaml | nindent 2 }}
---
{{- end }}
