{{- if .Values.serviceAccountName }}
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: sqluser-{{ .Values.serviceAccountName }}
  {{- if .Values.argoSyncWave }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.argoSyncWave | quote }}
  {{- end }}
  labels:
    {{- include "sqlinstance.labels" $ | nindent 4 }}
    {{- range $k, $v := $.Values.labels }}
    {{- printf "%s: %s" $k ($v | quote) | nindent 4 }}
    {{- end }}
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: "projects/{{ .Values.global.projectID }}"
  role: organizations/909834982171/roles/cloudsql.serviceaccount.access
  memberFrom:
    serviceAccountRef:
      name: {{ .Values.serviceAccountName }}
---
{{- end }}

