{{- if eq (len .Values.databases) 0 -}}
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  name: {{ .Values.name | lower }}
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
    {{- if .Values.argoSyncWave }}
    argocd.argoproj.io/sync-wave: {{ .Values.argoSyncWave | quote }}
    {{- end }}
  labels:
    {{- include "sqlinstance.labels" $ | nindent 4 }}
    {{- range $k, $v := $.Values.labels }}
    {{- printf "%s: %s" $k ($v | quote) | nindent 4 }}
    {{- end }}
spec:
  charset: UTF8
  collation: en_US.UTF8
  instanceRef:
    name: {{ .Values.name | lower }}

{{- else -}}

{{- range $db := .Values.databases }}
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  name: {{ $db.name }}
  {{- if or (not $db.deletionPolicyRemoveResource) ($db.annotations) ($.Values.argoSyncWave) }}
  annotations:
    {{- with $db.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if not $db.deletionPolicyRemoveResource }}
    cnrm.cloud.google.com/deletion-policy: abandon
    {{- end }}
    {{- if $.Values.argoSyncWave }}
    argocd.argoproj.io/sync-wave: {{ $.Values.argoSyncWave | quote }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "sqlinstance.labels" $ | nindent 4 }}
    {{- range $k, $v := $.Values.labels }}
    {{- printf "%s: %s" $k ($v | quote) | nindent 4 }}
    {{- end }}
spec:
  charset: {{ ($db.spec).charset | default "UTF8" }}
  collation: {{ ($db.spec).collation | default "en_US.UTF8" }}
  instanceRef:
    name: {{ $.Values.name | lower }}
---
{{- end -}}
{{- end -}}
