{{- if not .Values.databases -}}
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  name: {{ .Values.name  }}
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
    argocd.argoproj.io/sync-wave: {{ .Values.argoSyncWave | default "-5" | quote }}
  labels:
    {{- include "sqlinstance.labels" $ | nindent 4 }}
    {{- range $k, $v := .Values.labels }}
    {{- printf "%s: %s" $k ($v | quote) | nindent 4 }}
    {{- end }}
spec:
  charset: UTF8
  collation: en_US.UTF8
  instanceRef:
    name: {{ .Values.name }}

{{- else -}}

{{- range $db := .Values.databases }}
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  name: {{ $db.name }}
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
    argocd.argoproj.io/sync-wave: {{ $.Values.argoSyncWave | default "-5" | quote }}
  labels:
    {{- include "sqlinstance.labels" $ | nindent 4 }}
    {{- range $k, $v := $.Values.labels }}
    {{- printf "%s: %s" $k ($v | quote) | nindent 4 }}
    {{- end }}
spec:
  charset: {{ $db.charset | default "UTF8" }}
  collation: {{ $db.collation | default "en_US.UTF8" }}
  instanceRef:
    name: {{ $.Values.name | lower }}
---
{{- end -}}
{{- end -}}
