apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: {{ .Values.name | required "A SQL Instance resource name is required." }}
  {{- if or (not .Values.deletionPolicyRemoveResource) (.Values.annotations) (.Values.argoSyncWave) }}
  annotations:
    {{- with .Values.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if not .Values.deletionPolicyRemoveResource }}
    cnrm.cloud.google.com/deletion-policy: abandon
    {{- end }}
    {{- if .Values.argoSyncWave }}
    argocd.argoproj.io/sync-wave: {{ .Values.argoSyncWave | quote }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "sqlinstance.labels" . | nindent 4 }}
    {{- range $k, $v := $.Values.labels }}
    {{- printf "%s: %s" $k ($v | quote) | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.spec }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
