{{- if eq .Values.name "sqlinstance-sample" -}}
{{- fail (printf "you have not given your sqlinstance a proper name. [%s] " .Values.name) -}}
{{- end -}}

{{- include "sqlinstance.validate-availability-type" $ }}

apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: {{ .Values.name | required "A SQL Instance resource name is required." }}
  {{- if or (not .Values.deletionPolicyRemoveResource) (.Values.annotations) (.Values.argoSyncWave) }}
  annotations:
    {{- with .Values.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if not .Values.deletionPolicyRemoveResource }}
    cnrm.cloud.google.com/deletion-policy: abandon
    {{- end }}
    {{- if .Values.argoSyncWave }}
    argocd.argoproj.io/sync-wave: {{ .Values.argoSyncWave | quote }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "sqlinstance.labels" . | nindent 4 }}
    {{- range $k, $v := $.Values.labels }}
    {{- printf "%s: %s" $k ($v | quote) | nindent 4 }}
    {{- end }}
spec:
  databaseVersion: {{ .Values.databaseVersion }}
  region: europe-west3
  settings:
    availabilityType: {{ .Values.availabilityType }}
    tier: {{ include "sqlinstance.validate-tier" $ }}

    {{- with .Values.backupConfiguration }}
    backupConfiguration:
      backupRetentionSettings:
        retainedBackups: {{ .backupRetentionSettings.retainedBackups}}
      enabled: {{ .enabled }}
      location: eu
      pointInTimeRecoveryEnabled: {{ .pointInTimeRecoveryEnabled }}
      startTime: {{ .startTime }}
      transactionLogRetentionDays: {{ .transactionLogRetentionDays }}
    {{- end }}

    {{- with .Values.insightsConfig }}
    insightsConfig:
      queryInsightsEnabled: {{ .queryInsightsEnabled }}
      recordApplicationTags: {{ .recordApplicationTags }}
      recordClientAddress: {{ .recordClientAddress }}
    {{- end }}

    {{- with .Values.maintenanceWindow }}
    maintenanceWindow:
      day: {{ .day }}
      hour: {{ .hour }}
      updateTrack: {{ .updateTrack }}
    {{- end }}
    databaseFlags:
      - name: cloudsql.iam_authentication
        value: "on"
      - name: work_mem
        value: {{ include "sqlinstance.work-mem" $ }}
      {{- range $name, $value := .Values.databaseFlags }}
      - name: {{ $name }}
        value: {{ $value | quote }}
      {{- end }}
