{{- if .Values.serviceAccount }}
{{ $saName := .Values.serviceAccount | lower }}
{{ $projectID := (.Values.global.projectID | required "A project ID is required")}}
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  name: {{ .Values.serviceAccount }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.argoSyncWave | default "-5" | quote }}
  labels:
    {{- include "sqlinstance.labels" . | nindent 4 }}
    {{- range $k, $v := .Values.labels }}
    {{- printf "%s: %s" $k ($v | quote) | nindent 4 }}
    {{- end }}
spec:
  type: CLOUD_IAM_SERVICE_ACCOUNT
  instanceRef:
    name: {{ .Values.name }}
  resourceID: {{ $saName }}@{{ $projectID }}.iam
---
{{- end }}
