{{- if .Values.serviceAccountName }}
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  name: {{ .Values.serviceAccountName }}
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
    {{- if .Values.argoSyncWave }}
    argocd.argoproj.io/sync-wave: {{ .Values.argoSyncWave | quote }}
    {{- end }}
  labels:
    {{- include "sqlinstance.labels" $ | nindent 4 }}
    {{- range $k, $v := $.Values.labels }}
    {{- printf "%s: %s" $k ($v | quote) | nindent 4 }}
    {{- end }}
spec:
  type: CLOUD_IAM_SERVICE_ACCOUNT
  instanceRef:
    name: {{ .Values.name }}
  resourceID: {{ .Values.serviceAccountName }}@{{ .Values.global.projectID | required "A project ID is required" }}.iam
---
{{- end }}
