{{- include "sqlinstance.validateNoDuplicateServiceAccounts" . -}}

{{- range $sa := (default (list) .Values.serviceAccounts) }}
{{- $projectID := $.Values.global.projectID | required "A project ID is required" -}}
{{- $resourceID := (ternary $sa.email (printf "%s@%s.iam.gserviceaccount.com" $sa.name $projectID) (hasKey $sa "email")) -}}
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  name: {{ default $sa.name $sa.email | replace "@" "-" | replace "." "-" | trunc 63 | trimSuffix "-" }}
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
    {{- if $.Values.argoSyncWave }}
    argocd.argoproj.io/sync-wave: {{ $.Values.argoSyncWave | quote }}
    {{- end }}
  labels:
    {{- include "sqlinstance.labels" $ | nindent 4 }}
    {{- range $k, $v := $.Values.labels }}
    {{- printf "%s: %s" $k ($v | quote) | nindent 4 }}
    {{- end }}
spec:
  type: CLOUD_IAM_SERVICE_ACCOUNT
  instanceRef:
    name: {{ $.Values.name }}
  resourceID: {{ $resourceID }}
---
{{- end }}

{{- if and .Values.serviceAccountName (ne .Values.serviceAccountName "sqlinstance-sa") }}
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  name: {{ .Values.serviceAccountName }}
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
    {{- if .Values.argoSyncWave }}
    argocd.argoproj.io/sync-wave: {{ .Values.argoSyncWave | quote }}
    {{- end }}
  labels:
    {{- include "sqlinstance.labels" $ | nindent 4 }}
    {{- range $k, $v := $.Values.labels }}
    {{- printf "%s: %s" $k ($v | quote) | nindent 4 }}
    {{- end }}
spec:
  type: CLOUD_IAM_SERVICE_ACCOUNT
  instanceRef:
    name: {{ .Values.name }}
  resourceID: {{ .Values.serviceAccountName }}@{{ .Values.global.projectID | required "A project ID is required" }}.iam
---
{{- end }}
