# Default values for sqlinstance.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# https://cloud.google.com/config-connector/docs/reference/resource-docs/sql/sqlinstance

global:
  # Add labels from a parent chart to all manifests.
  # Google Cloud labels only support hyphens (-), underscores (_), lowercase characters and numbers.
  labels: {}

  # The Google Project ID.
  projectID: null

######################################################
#                    SQL Instance                    #
######################################################

name: sqlinstance-sample

# Uncomment below line to delete the SQL Instance in Google on Kubernetes object deletion.
#deletionPolicyRemoveResource: true

# Below property sets a ArgoCD Sync Wave annotation on all resources. Set it to "false" to disable it.
# https://argo-cd.readthedocs.io/en/stable/user-guide/sync-waves/
argoSyncWave: -5

# Labels on the Config Connector resource.
# Google Cloud labels only support hyphens (-), underscores (_), lowercase characters and numbers.
labels: {}

# Annotations on the Config Connector resource.
annotations: {}

databaseVersion: POSTGRES_17
tier: db-f1-micro

# Can still be used for service accounts inside the same KNP as the Database.
# Use "serviceAccounts" to add multiple, and gain support for IAM SA's from outside the KNP. 
# Do NOT use this together with "serviceAccounts". The serviceAccountName is only kept for backwards compatibility.
serviceAccountName: sqlinstance-sa

# The name of the service account that gets access to the SQL Instance.
# This referes to the id of the SA without the "@<projectid>.iam.gserviceaccount.com"
# serviceAccounts: []
# When granting access to IAM SA inside the same KNP as the database, use the name.
#  - name: sqlinstance-sa
# When granting access to IAM SA outside the KNP as the database, use the email.
#  - email: sqlinstance-sa@<projectid>.iam.gserviceaccount.com

# Possible values are REGIONAL for high availability or ZONAL for a single zone instance.
# Recommendation id to use REGIONAL for production use and ZONAL for test.
availabilityType: REGIONAL

# The following properties are for making it possible to connect from the Horizon Clusters, to the SQLInstances in your KNP's. 
# In order to connect from the Horizon Clusters to the SQLInstances on GCP Gen1, you need to use Private Service connect (PSC).
# Prerequisites: 
# Set global.projectID
# Follow these instructions stricly to set it up correctly:
# 1. You need to first prepare the SQLInstance for Private Service Connect (PSC), by toggling preparePSC to true, merge to master, sync in ArgoCD and wait for the update of the DB to finish.
preparePSC: false
# 2. Then you can enable Private Service Connect (PSC) by toggling the enablePSC value to true, merge to master, sync in ArgoCD and wait for the update of the DB to finish.
enablePSC: false

backupConfiguration:
  backupRetentionSettings:
    retainedBackups: 8
  enabled: true
  pointInTimeRecoveryEnabled: true
  startTime: 01:00
  transactionLogRetentionDays: 7

insightsConfig:
  queryInsightsEnabled: true
  recordApplicationTags: true
  recordClientAddress: true

maintenanceWindow:
  day: 7
  hour: 02
  updateTrack: stable

# NB: Some database flags will force a reboot of the Instance.
# https://cloud.google.com/sql/docs/postgres/flags
databaseFlags: []
  # cloudsql.logical_decoding: "on"

######################################################
#                     Databases                      #
######################################################

# If you leave the "databases" array empty, a default database with the same name as the SQL Instance will be created, with default values.
# If you want another database name or create multiple datebases, add them to the array below with minimum a name. Examples are provided.

databases: []
  # - name: database-01

  # - name: database-02
  #   deletionPolicyRemoveResource: true
  #   annotations:
  #     some-annotation: some-value
  #   spec:
  #     charset: some-other-value
  #     collation: some-other-value
