name: Chart Releaser Dev - SQL Instance

on:
  workflow_dispatch:
  push:
    paths:
      - 'charts/sqlinstance/**'

jobs:
  chart-releaser-google-registry:
    uses: ./.github/workflows/chart-releaser-google-registry.yml
    secrets: inherit
    with:
      helmChartPath: charts/sqlinstance