name: Chart Releaser Dev - Pub Sub

on:
  workflow_dispatch:
  push:
    paths:
      - 'charts/pub-sub/**'

jobs:
  chart-releaser-google-registry:
    uses: ./.github/workflows/chart-releaser-google-registry.yml
    secrets: inherit
    with:
      helmChartPath: charts/pub-sub