name: Chart Releaser Dev - Big Query

on:
  workflow_dispatch:
  push:
    paths:
      - 'charts/big-query/**'

jobs:
  chart-releaser-google-registry:
    uses: ./.github/workflows/chart-releaser-google-registry.yml
    secrets: inherit
    with:
      helmChartPath: charts/big-query